spring:
  config:
    import:
      - optional:file:../.local/barberturno.env[.properties]
      - optional:file:./.local/barberturno.env[.properties]
  datasource:
    url: ${BT_DB_URL:jdbc:postgresql://localhost:5433/barberturno}
    username: ${BT_DB_USER:barberturno}
    password: ${BT_DB_PASSWORD}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    pe.barberturno: DEBUG

barberturno:
  seguridad:
    jwt-secret: ${BT_JWT_SECRET:}
    cookie-secure: ${BT_COOKIE_SECURE:false}

  admin:
    correo: ${BT_ADMIN_CORREO:}
    password: ${BT_ADMIN_PASSWORD:}
    nombre: ${BT_ADMIN_NOMBRE:}
