#!/usr/bin/env node
/**
 * LOC físicas propias para RA-02 (métrica informativa) y RA-03, sin dependencias (Node 20 y 24).
 * Cuenta una línea si conserva algún carácter no blanco al retirar comentarios.
 * No es un parser: plantillas TS opacas, incluidas sus interpolaciones;
 * no analiza interpolaciones anidadas, regex TS ni dollar quoting SQL.
 */
import { readdir, readFile, mkdir, appendFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { dirname, join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isDeepStrictEqual } from 'node:util';

const RAIZ = dirname(dirname(fileURLToPath(import.meta.url)));
const RUTAS = ['backend/src', 'frontend/src', 'frontend/e2e', 'perf'];
const EXTENSIONES = {
  '.java': 'Java', '.ts': 'TS', '.html': 'HTML',
  '.scss': 'SCSS', '.css': 'CSS', '.sql': 'SQL',
};
const DIRECTORIOS_EXCLUIDOS = new Set([
  'node_modules', 'target', 'dist', '.angular', 'docs', '.git', '.local',
]);
// Paletas generadas por el schematic de Angular Material, no autoría propia.
const GENERADOS_EXPLICITOS = new Set(['frontend/src/theme-colors.scss']);
// Convención auditable para futuros generados: solo las primeras cinco líneas.
const MARCA_GENERADO = /Generado con|Generated by/i;
const citar = texto => '\x60' + texto + '\x60';

function contarLineas(texto, extension) {
  const fuente = texto.replace(/\r\n?/g, '\n');
  let estado = 'codigo';
  let delimitador = '';
  let enEtiquetaHtml = false;
  let lineas = 0;
  let tieneCodigo = false;

  for (let i = 0; i < fuente.length;) {
    const caracter = fuente[i];
    if (caracter === '\n') {
      if (tieneCodigo) lineas++;
      tieneCodigo = false;
      if (estado === 'linea') estado = 'codigo';
      i++;
      continue;
    }
    if (estado === 'linea') {
      i++;
      continue;
    }
    if (estado === 'bloque') {
      if (fuente.startsWith(delimitador, i)) {
        i += delimitador.length;
        estado = 'codigo';
      } else {
        i++;
      }
      continue;
    }
    if (estado === 'literal') {
      if (/\S/.test(caracter)) tieneCodigo = true;
      // SQL: '' o "" representa una comilla dentro del literal/identificador.
      if (extension === '.sql' && fuente.startsWith(delimitador.repeat(2), i)) {
        i += 2;
      } else if (caracter === '\\' && ['.java', '.ts', '.scss', '.css'].includes(extension)) {
        // Conservar el salto físico de línea, incluso si está escapado.
        if (i + 1 < fuente.length && fuente[i + 1] !== '\n') i += 2;
        else i++;
      } else if (fuente.startsWith(delimitador, i)) {
        i += delimitador.length;
        estado = 'codigo';
      } else {
        i++;
      }
      continue;
    }

    if (extension === '.html' && fuente.startsWith('<!--', i)) {
      estado = 'bloque';
      delimitador = '-->';
      i += 4;
    } else if (extension !== '.html' && fuente.startsWith('/*', i)) {
      estado = 'bloque';
      delimitador = '*/';
      i += 2;
    } else if (
      (['.java', '.ts', '.scss'].includes(extension) && fuente.startsWith('//', i))
      || (extension === '.sql' && fuente.startsWith('--', i))
    ) {
      estado = 'linea';
      i += 2;
    } else if (extension === '.java' && fuente.startsWith('"""', i)) {
      tieneCodigo = true;
      estado = 'literal';
      delimitador = '"""';
      i += 3;
    } else if (
      (extension !== '.html' || enEtiquetaHtml)
      && (caracter === '"' || caracter === "'"
      || (extension === '.ts' && caracter === '\x60'))
    ) {
      tieneCodigo = true;
      estado = 'literal';
      delimitador = caracter;
      i++;
    } else {
      // En HTML, los apóstrofos del texto no abren atributos entre comillas.
      if (extension === '.html' && caracter === '<') enEtiquetaHtml = true;
      if (extension === '.html' && caracter === '>') enEtiquetaHtml = false;
      if (/\S/.test(caracter)) tieneCodigo = true;
      i++;
    }
  }
  return lineas + Number(tieneCodigo);
}

function clasificar(ruta) {
  if (ruta.startsWith('perf/')) return 'carga';
  if (ruta.startsWith('backend/src/test/') || ruta.endsWith('.spec.ts')
      || ruta.startsWith('frontend/e2e/')) return 'pruebas';
  return 'producto';
}

async function medir(raiz) {
  const archivos = [];
  const excluidos = [];
  const ausentes = [];
  const excluir = (ruta, motivo) => excluidos.push({ ruta, motivo });

  async function recorrer(ruta) {
    const entradas = await readdir(join(raiz, ruta), { withFileTypes: true });
    entradas.sort((a, b) => a.name.localeCompare(b.name, 'en'));
    for (const entrada of entradas) {
      const archivo = ruta + '/' + entrada.name;
      if (entrada.isSymbolicLink()) {
        excluir(archivo, 'Enlace simbólico: no se sigue fuera del alcance');
      } else if (entrada.isDirectory()) {
        if (DIRECTORIOS_EXCLUIDOS.has(entrada.name)) {
          excluir(archivo + '/', 'Dependencias, salida, documentación o datos locales');
        } else {
          await recorrer(archivo);
        }
      } else if (entrada.isFile()) {
        const extension = extname(archivo);
        if (!Object.hasOwn(EXTENSIONES, extension)) {
          excluir(archivo, 'Extensión fuera del cálculo');
          continue;
        }
        if (GENERADOS_EXPLICITOS.has(archivo)) {
          excluir(archivo, 'Generado explícito: schematic de Angular Material');
          continue;
        }
        const texto = await readFile(join(raiz, archivo), 'utf8');
        if (MARCA_GENERADO.test(texto.split(/\r\n?|\n/).slice(0, 5).join('\n'))) {
          excluir(archivo, 'Marca de generado en las primeras cinco líneas');
          continue;
        }
        archivos.push({
          ruta: archivo, lenguaje: EXTENSIONES[extension],
          clase: clasificar(archivo), lineas: contarLineas(texto, extension),
        });
      }
    }
  }

  for (const ruta of RUTAS) {
    try {
      await recorrer(ruta);
    } catch (error) {
      // Solo la ausencia de la raíz es admisible; errores de lectura internos fallan.
      if (error.code === 'ENOENT' && error.path === join(raiz, ruta)) ausentes.push(ruta);
      else throw error;
    }
  }
  const vacio = () => ({ producto: 0, pruebas: 0, carga: 0, total: 0 });
  const lenguajes = Object.fromEntries(Object.values(EXTENSIONES).map(l => [l, vacio()]));
  const totales = vacio();
  for (const archivo of archivos) {
    for (const contador of [lenguajes[archivo.lenguaje], totales]) {
      contador.total += archivo.lineas;
      if (archivo.clase === 'producto') contador.producto += archivo.lineas;
      else contador.pruebas += archivo.lineas;
      if (archivo.clase === 'carga') contador.carga += archivo.lineas;
    }
  }
  const porcentaje = (java, total) => total === 0 ? null : 100 * java / total;
  return {
    lenguajes, totales,
    porcentajeJavaConPruebas: porcentaje(lenguajes.Java.total, totales.total),
    porcentajeJavaSinPruebas: porcentaje(lenguajes.Java.producto, totales.producto),
    archivos, excluidos, ausentes,
  };
}

function tabla(resultado) {
  const porcentaje = valor => valor === null ? 'No aplica (denominador cero)' : valor.toFixed(2) + ' %';
  const filas = Object.entries(resultado.lenguajes).concat([['Total', resultado.totales]]);
  return [
    '## Medición · ' + resultado.fecha + ' · commit ' + resultado.commit,
    '',
    'Node: ' + resultado.node + '. Raíces: ' + RUTAS.map(citar).join(', ') + '.',
    'Extensiones contadas: ' + Object.keys(EXTENSIONES).join(', ') + '.',
    'LOC físicas sin líneas vacías ni comentarios; las cadenas conservan sus marcadores de comentario.',
    'Fuera del cálculo: JSON/YAML de configuración, package-lock.json, mvnw*, Markdown, docs, dependencias y generados.',
    '',
    '| Lenguaje | Producto | Pruebas | Carga (incluida en pruebas) | Total |',
    '|---|---:|---:|---:|---:|',
    ...filas.map(([nombre, c]) => '| ' + [nombre, c.producto, c.pruebas, c.carga, c.total].join(' | ') + ' |'),
    '',
    '**Java con pruebas:** ' + porcentaje(resultado.porcentajeJavaConPruebas) + ' (Java total ÷ total).',
    '**Java sin pruebas:** ' + porcentaje(resultado.porcentajeJavaSinPruebas) + ' (Java de producto ÷ producto).',
    'La carga se informa aparte como subconjunto de pruebas y se suma una sola vez al total.',
    '',
    '### Exclusiones auditables',
    '',
    ...resultado.excluidos.map(a => '- ' + citar(a.ruta) + ': ' + a.motivo + '.'),
    ...(resultado.excluidos.length ? [] : ['Ninguna.']),
    '',
    'Raíces aún ausentes: ' + (resultado.ausentes.join(', ') || 'ninguna') + '.',
    '',
    'Límites léxicos: plantillas TS opacas (incluidas interpolaciones), sin interpolaciones anidadas ni regex TS; SQL sin dollar quoting.',
    'Se mide el árbol de trabajo; el commit identifica HEAD y no certifica ausencia de cambios locales.',
    '',
  ].join('\n');
}

async function main() {
  const argumentos = new Set(process.argv.slice(2));
  for (const argumento of argumentos) {
    if (!['--json', '--escribir', '--verificar-fixtures'].includes(argumento)) {
      throw new Error('Opción desconocida: ' + argumento);
    }
  }
  if (argumentos.has('--verificar-fixtures')) {
    if (argumentos.size !== 1) throw new Error('--verificar-fixtures se usa sin otras opciones.');
    const raizFixtures = join(RAIZ, 'tools/fixtures-medicion');
    const esperado = JSON.parse(await readFile(join(raizFixtures, 'esperado.json'), 'utf8'));
    const obtenido = await medir(raizFixtures);
    if (!isDeepStrictEqual(obtenido, esperado)) {
      console.error('Fixtures distintos del resultado esperado.');
      console.error(JSON.stringify({ esperado, obtenido }, null, 2));
      process.exitCode = 1;
      return;
    }
    console.log('Fixtures correctos: ' + obtenido.archivos.length + ' archivos contados, '
      + obtenido.excluidos.length + ' exclusiones; conteos, clasificación y porcentajes coinciden.');
    return;
  }
  const resultado = {
    fecha: new Date().toISOString(),
    commit: execFileSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: RAIZ, encoding: 'utf8' }).trim(),
    node: process.version, raices: RUTAS, extensiones: EXTENSIONES,
    ...await medir(RAIZ),
  };
  const markdown = tabla(resultado);
  if (argumentos.has('--escribir')) {
    const destino = join(RAIZ, 'docs/pruebas/medicion-java.md');
    await mkdir(dirname(destino), { recursive: true });
    const introduccion = '# Medición del porcentaje de Java\n\n'
      + 'RA-02 es una métrica informativa, sin umbral (reclasificada por el responsable el 04/10/2026). RA-03 exige una medición reproducible.\n'
      + 'Se excluyen dependencias, generados, comentarios, líneas vacías y documentación. '
      + 'Se informan las variantes con y sin pruebas, incluyendo HTML, SCSS/CSS y SQL. '
      + 'P-02 está resuelta: el requisito es el backend en Java; el porcentaje solo se informa.\n\n'
      + 'Repetir con ' + citar('node tools/medir-java.mjs --escribir') + '; cada ejecución añade una sección fechada. '
      + 'Las plantillas TS se tratan como literales opacos, sin analizar interpolaciones anidadas. '
      + 'No se analizan regex TS ni dollar quoting SQL.\n\n';
    try {
      await appendFile(destino, introduccion + markdown, { encoding: 'utf8', flag: 'wx' });
    } catch (error) {
      if (error.code !== 'EEXIST') throw error;
      await appendFile(destino, '\n' + markdown, 'utf8');
    }
  }
  console.log(argumentos.has('--json') ? JSON.stringify(resultado, null, 2) : markdown);
}

main().catch(error => {
  console.error('No se pudo medir Java: ' + error.message);
  process.exitCode = 1;
});
